[colors]
ansi = [
  "#6a6a6a",
  "#e05661",
  "#1da912",
  "#eea825",
  "#118dc3",
  "#9a77cf",
  "#56b6c2",
  "#fafafa",
]
background = "#fafafa"
brights = [
  "#bebebe",
  "#e88189",
  "#25d717",
  "#f2bb54",
  "#1caceb",
  "#b69ddc",
  "#7bc6d0",
  "#ffffff",
]
cursor_bg = "#9a77cf"
cursor_fg = "#fafafa"
foreground = "#6a6a6a"
selection_bg = "#9a77cf"
selection_fg = "#6a6a6a"

[colors.tab_bar]
inactive_tab_edge = "#fafafa"
background = "#fafafa"

[colors.tab_bar.active_tab]
fg_color = "#9a77cf"
bg_color = "#fafafa"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#bebebe"
bg_color = "#fafafa"
intensity = "Bold"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#9a77cf"
bg_color = "#fafafa"

[colors.tab_bar.new_tab]
fg_color = "#9a77cf"
bg_color = "#fafafa"

[colors.tab_bar.new_tab_hover]
fg_color = "#fafafa"
bg_color = "#9a77cf"

[colors.indexed]
59 = "#bebebe"
100 = "#e2be7d"
214 = "#ee9025"

[metadata]
name = "onedarkpro_onelight"
origin_url = "https://github.com/olimorris/onedarkpro.nvim"
