# nightfly theme for WezTerm
#
# Upstream: github.com/bluz71/vim-nightfly-colors
#
# Usage: copy this theme into the colors directory and then select the nightfly
# 'color_scheme' in your 'wezterm.lua' configuration.

[metadata]
name = "nightfly"
origin_url = "https://github.com/bluz71/vim-nightfly-colors"

[colors]
background = "#011627"
foreground = "#bdc1c6"
cursor_bg = "#9ca1aa"
cursor_fg = "#080808"
cursor_border = "#9ca1aa"
selection_bg = "#b2ceee"
selection_fg = "#080808"
scrollbar_thumb = "#9ca1aa"
split = "#9ca1aa"

ansi = [
  "#1d3b53",
  "#fc514e",
  "#a1cd5e",
  "#e3d18a",
  "#82aaff",
  "#c792ea",
  "#7fdbca",
  "#a1aab8",
]
brights = [
  "#7c8f8f",
  "#ff5874",
  "#21c7a8",
  "#ecc48d",
  "#82aaff",
  "#ae81ff",
  "#7fdbca",
  "#d6deeb",
]

compose_cursor = "#e3d18a"
visual_bell = "#e3d18a"
